### PR TITLE
Add breakpoint axis to map

### PR DESCRIPTION
**Pull request by Sonje**
Continued work: https://github.com/HabitatMap/AirCasting/pull/695

### Implements:
- Decoupled Threshold configurator from header toggle
- Extends existing threshold configurator to handle three design versions with different reset button options: I called the legend one "color boxes" and this design makes thumbs static, the old mobile view is called old mobile styles, and if they are not called explicitly we are using the default new threshold.
- Adds threshold to session details modal open view (using the old style)
- Improved styling of the threshold on the map view
- Adds Mobile Legend button to mobile map view and modal with a static 
- Decoupled slider and reset button logic from threshold configurator
- Mobile Legend uses new User Settings instead of map slice
- Adjusted reset button styling for calendar and it now uses header toggle 
- Adds an option to modify reset button colour theme as per designs

### Fixes:
- removed blue dots appearing on input range element (https://trello.com/c/JnK3WxOO/1921-mobile-device-view-mobile-session-ui-improvements)
- removed caret sometimes appearing around input range
- significantly improved performance when moving slider thumbs
- changed a threshold position on map view to fixed to make sure it stays in one place even when a user opens/hides address bar at the bottom (https://trello.com/c/JnK3WxOO/1921-mobile-device-view-mobile-session-ui-improvements)

### Related tickets:

1. https://trello.com/c/CnZ0eR7N/1835-session-details-reset-to-default-breakpoint-values
2. https://trello.com/c/badEQ2hN/1839-map-reset-to-default-breakpoint-values
3. https://trello.com/c/JnK3WxOO/1921-mobile-device-view-mobile-session-ui-improvements

### Screenshots:
Mobile Legend threshold:
image

Desktop Map View threshold:
image

Mobile Session details threshold:
image

### CODE REVIEW

**Comment by Sonje** [comment]
[Breakpoint Axis on the Map](https://trello.com/c/QtOssfqV/1838-breakpoint-axis-on-the-map)

**Comment by Sonje** [comment]
[Session Details: Reset to Default Breakpoint Values](https://trello.com/c/CnZ0eR7N/1835-session-details-reset-to-default-breakpoint-values)

**Comment by Sonje** [comment]
Update: @evulins & @JoannaThelema - I forgot to clean up the legendOpen remnants from Map Slice, it's now removed

**Comment by Sonje** [comment]
@evulins & @JoannaThelema 2nd update - I've noticed there were still remnants of the blue dot on input ranges, so I had to add additional manual css removals around track. It's deployed to experimental so you can notice on android phones they no longer appear. Hopefully that's the last update. Have a great weekend!

**Review by JoannaThelema — APPROVED** [review]
Uff... Huge rework 💪  I didn't dig into the details of this PR because it's really big. In the future, we definitely need to find a way to split such massive refactors into smaller, more manageable parts 😅

**Pull request merged**
