### PR TITLE
Go back to the session list on button click

### PR DESCRIPTION
**Pull request by bazelajoanna**
Return to the sessions list on "Go back" button click.

https://github.com/HabitatMap/AirCasting/assets/51509583/e9769b4e-abbe-43f0-a11c-0688c8a71a4a

### CODE REVIEW

**Comment by JoannaThelema** [comment]
Screenshot 2024-06-26 at 14 51 22

**Comment by JoannaThelema** [comment]
https://github.com/HabitatMap/AirCasting/assets/24482637/96058a43-832e-4d75-8b6e-f280a87c588f

**Comment by JoannaThelema** [comment]
https://github.com/HabitatMap/AirCasting/assets/24482637/3dd118c0-8e2d-4c9b-b7de-d5badd25b0b0

**Comment by bazelajoanna** [comment]
Changes in review changes:
- main width for desktop is 1024px, that's the width useScreenSizeDetection function checks by default,
- tresholds in modal are visible on desktop only

**Review by JoannaThelema — APPROVED** [review]
Tested and approved 🙌

**Review by evulins — APPROVED** [review]
🥇 💯

**Pull request merged**
