### PR TITLE
UI: Single session tweaks

### PR DESCRIPTION
**Pull request by gitjul**
- remove excessive whitespace below zoom buttons
- change hover state of zoom button to blue - before when hovering on
  active element it became white which was counterintuitive because
clicking on it doesn't turn it off
- slimmer scrollbar
- pointer cursor on scroll thumb and arrows
- clip session names to two lines
- restructure html to improve the flex layout, align columns
- rename classes using bem-style
- align the button of thescrollbar with the bottom ofaction buttons
- fix credits position after changes
- move close button away from credits so that users don't mistakenly click the credits when they want to close the session and vice versa
- fix close button broken in Safari

One requested change wasn't possible to fix: making the whole area of zoom buttons clickable.
I submitted an issue with Highcharts: https://github.com/highcharts/highcharts/issues/10986

Before - one line name:

Screenshot 2019-06-13 at 15 09 09

Before - three line name:

Screenshot 2019-06-13 at 16 12 45

After - one line name:

Screenshot 2019-06-13 at 16 13 46

After - three line name (Chrome, webkit):

Screenshot 2019-06-13 at 16 10 28

After - threee line name (FF 67 - in 68 line-clip will work):

Screenshot 2019-06-13 at 16 10 38

### CODE REVIEW

**Comment by gitjul** [comment]
todo separately: shrink zoom buttons

**Comment by 3v0k4** [comment]
👁

**Comment by 3v0k4** [comment]
I think we are using in the code both "single session" and "selected session" for the same case. What would you use if we needed to choose?

**Comment by gitjul** [comment]
yeah, I've been getting confused by this. "single session" is what I'd choose.

**Pull request merged**
