### PR TITLE
Redirects

### PR DESCRIPTION
**Pull request by AkkarinForest**
- [x] - redirect static pages to habitatmap.org
- [x] - remove old html and assets
- [ ] - change navigation bar according to this: https://projects.invisionapp.com/share/BZT8CXB8M4W#/screens/379469481
- [ ] - if possible remove code from app/views/shared (footer, nav, ...) and their assets

### CODE REVIEW

**Comment by 3v0k4** [comment]
I see some changes related to graph, notes and export by uuid that seem unrelated to what's described in this PR changes. Do you remember what was that about @AkkarinForest ?

**Comment by AkkarinForest** [comment]
These other changes are already on master and are unrelated to this PR. I guess the commit sha was different due to some rebasing, so github didn't recognize them. Anyway, I rebased with maser and everything is as it should be.

**Comment by 3v0k4** [comment]
Taking over in https://github.com/HabitatMap/AirCasting/pull/376. The redirects are at the Apache level. Thanks Alex!

**Comment by 3v0k4** [comment]
Taking over in #376. The redirects are at the Apache level. Thanks Alex!

**Pull request closed without merging**
